services:
  postgres:
    image: postgres:alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    networks:
      - app
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database_postgres_setup.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PASSWORD}
    volumes:
      - cache:/data

volumes:
  postgres-db:
  cache:
    driver: local

networks:
  app: